stages:
- build
- trigger_deploy

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE"
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"

build:
  stage: build
  image: docker:20.10.16
  services:
  - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .
  - docker push "$IMAGE_NAME:$IMAGE_TAG"
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

trigger_deploy:
  stage: trigger_deploy
  image: ruby:3.1
  script:
  - 'curl -X POST -F token=$CI_JOB_TOKEN -F ref=$CI_DEFAULT_BRANCH -F "variables[IMAGE_NAME_APP2]=$IMAGE_NAME" -F "variables[IMAGE_TAG_APP2]=$IMAGE_TAG" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline"'
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
